server {
    listen 80;
    
    # Serve o seu Frontend (React/Vue/Angular)
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy Reverso: Redireciona chamadas para o Backend
    location /api/ {
        # O Docker DNS resolve automaticamente o nome do serviço 'backend'
        proxy_pass http://backend:5000/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}